package pfpsc.constant;

public enum EntityPropertyConstant {
	//用户状态
	USER_STATE_ACTIVE,
	USER_STATE_BANNED,
	//用户属性
	USER_PROPERTY_CUSTOMER,
	USER_PROPERTY_SHOPPER,
	USER_PROPERTY_ADMINISTRATOR,
	USER_PROPERTY_TEMPORARY,
	//订单状态
	ORDER_STATE_CREATING,
	ORDER_STATE_UNPAID,
	ORDER_STATE_PENDING,
	ORDER_STATE_READY,
	ORDER_STATE_WITHDRAWING,
	ORDER_STATE_FINISHED,
	ORDER_STATE_CANCELLED,
	//商店状态
	SHOP_STATE_OPENING,
	SHOP_STATE_CLOSED,
	SHOP_STATE_PENDING,
	SHOP_STATE_BANNED,
}
